spring:
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false

server:
  port: 4028
  error:
    whitelabel:
      enabled: false
  connection-timeout: 5s

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic


